name: PR - Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Allow concurrent pipelines on dev branch to ensure they always complete without being cancelled, which is useful when tracing back failures
    concurrency:
      group: ${{ github.ref }}-unit-tests
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
